drop table if exists class CASCADE;
drop table if exists mark CASCADE;
drop table if exists student CASCADE;
drop table if exists teacher CASCADE;

create table class (id bigint generated by default as identity, name varchar(255), primary key (id));
create table mark (id bigint generated by default as identity, mark double not null, month varchar(255), subject varchar(255), student_id bigint, teacher_id bigint, primary key (id));
create table student (id bigint generated by default as identity, gender varchar(255), student_name varchar(255), class_name_id bigint, primary key (id));
create table teacher (id bigint generated by default as identity, gender varchar(255), name varchar(255), subject varchar(255), primary key (id));

alter table mark add constraint student_id foreign key (student_id) references student;
alter table mark add constraint teacher_id foreign key (teacher_id) references teacher;
alter table student add constraint class_id foreign key (class_name_id) references class;